### Image Response
GET https://resources.jetbrains.com/help/img/idea/2023.1/http_request_name.png

### PDF Response
GET https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf

### HTML Preview
GET https://www.jetbrains.com/help/idea/http-client-cli.html

//TIP For opening HTML preview, click <b>&lt;Show Preview&gt;</b> button near response file name, or click <icon src="AllIcons.General.LayoutPreviewOnly"/> button on action toolbar
